FasterXML/jackson-jaxrs-providers

json/src/test/java/com/fasterxml/jackson/jaxrs/json/dw/SimpleEndpointTestBase.java
We just upgraded from Jackson 2.1.1 to Jackson 2.3.5 and encountered a regression in the way dynamic typing is handled. It seems that if you have a resource that returns a list, static typing is always used to serialize the list contents, even though the mapper has dynamic typing enabled. Returning a single object works fine (dynamic typing is used), it is only once you wrap in a list that the problem occurs. This PR adds two tests. The first one returns a single object and passes, and the second one returns a list and fails (the `z` field isn't serialized because of static typing). This test fails when running Jackson 2.3.5, 2.4.5, 2.5.1, and against master (but this behavior worked in 2.1.1).
I think the issue arises because `ProviderBase` calls `withType` …
=> Add failing test for dynamic typing

base/src/main/java/com/fasterxml/jackson/jaxrs/base/ProviderBase.java
@cowtowncoder I tried to use the configure method that accepts a `JaxRSFeature` but it didn't have any effect. After banging my head against a wall for a little bit I looked inside the method and saw that it was ignoring the `boolean state` parameter and just always enabled the feature. This PR updates the configure method to properly enable/disable based on the boolean parameter and also removes a bunch of extraneous boolean arguments that were also unused.
=> Fix feature methods

cbor/pom.xml, json/pom.xml, smile/pom.xml, xml/pom.xml
Update the jackson-jaxrs-providers to provide additional jars for each
of the providers which do not include the META-INF/services files. This
will allow using the providers in situations where auto-registration is
not desired. Fixes issue #39.
=> Provide alternate jars without META-INF/services.

smile/pom.xml, xml/pom.xml, yaml/pom.xml
#71 added the missing `com.fasterxml.jackson.databind.cfg` OSGi import to the `json` module but the `smile`, `yaml`, and `xml` modules also need this import.
Note that you should be able to use wildcards in your "osgi.import" instructions and the bundleplugin will expand them based on what's referenced in the compiled bytecode. Often people will leave a dangling `*` wildcard at the end as a catch-all in case they forget to update their imports when refactoring.
=> add missing OSGi import to smile, yaml, and xml modules

base/src/main/java/com/fasterxml/jackson/jaxrs/base/ProviderBase.java, json/src/test/java/com/fasterxml/jackson/jaxrs/json/dw/SimpleEndpointTestBase.java
Notes :  
- the pom of module jackson-jaxrs-json-provider contains both jersey and resteasy dependency for test purpose. However at runtime because of the the way  JAX-RS services such as `RuntimeDelegate` are loaded (SPI) you can start a jersey server but use service of Resteasy instead of jersey ones (`org.jboss.resteasy.spi.ResteasyProviderFactory` instead of `org.glassfish.jersey.internal.RuntimeDelegateImpl` for example). 
So for the `com.fasterxml.jackson.jaxrs.json.jersey.SimpleEndpointTest.testDynamicTypingPages()` resteasy dependency must be removed of the pom to actually observe the issue and the fix.
- Second observation is that if you annotate `Page ` class with ` @JsonTypeInfo(use=JsonTypeInfo.Id.CLASS, include=JsonTypeInfo.As.PROPERTY, property="@class")` the test pass …
=> Fix issue#87 and add unit test

base/src/main/java/com/fasterxml/jackson/jaxrs/base/NoContentExceptionSupplier.java, base/src/main/java/com/fasterxml/jackson/jaxrs/base/ProviderBase.java, base/src/main/java/com/fasterxml/jackson/jaxrs/base/nocontent/JaxRS1NoContentExceptionSupplier.java, base/src/main/java/com/fasterxml/jackson/jaxrs/base/nocontent/JaxRS2NoContentExceptionSupplier.java
As discussed here https://github.com/FasterXML/jackson-jaxrs-providers/issues/90
Implemented approach with a dynamic selection of NoContentException creation strategy.
I did it in a bit another fashion than it was implemented previously to use reflection only once for a strategy selection, not for a creation of each instance.
Result:
```
CONFIG:     Provider found: class com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider
```
During a container start.
Also, here https://github.com/Spikhalskiy/jackson-jaxrs-providers-compat-tests
is a separate module that depends on the old JaxRs and Jersey dependencies version. Test there fails on current master and works fine with this PR merged. Feel free to just pick it up as one more github.com/Jackson module.
=> Implemented dynamic selection of NoContentException provider to back support of JaxRS 1.x

pom.xml
This PR fixes #93 by doing two things:
* Update to the latest maven-bundle-plugin
* Remove the -nouses instruction which suppressed the necessary metadata
I'm not personally a fan of the maven-bundle plugin, but I understand the reluctance to move to a different build plugin in an otherwise stable project, so I've simply moved to a more up-to-date version which has better handling for annotation dependencies. 
The other thing that I've done is to re-enable the generation of uses clauses for package exports (i.e. to go back to the default configuration value). I'm not sure why this feature has been disabled throughout the Jackson project, as it means that all of the Jackson bundles are at risk of runtime failures (ranging from missing annotations to Linkage Errors). This feature really …
=> Update OSGi build metadata to fix missing uses clause

cbor/src/moditect/module-info.java, datatypes/src/moditect/module-info.java, smile/src/moditect/module-info.java, xml/src/moditect/module-info.java, yaml/src/moditect/module-info.java
Hi,
please consider merging this PR which extends #121 to all providers, so that they could be leveraged in modularized applications using newer version of JAX-RS while remaining backward compatible. 
I've encountered the problem with `jackson-jaxrs-xml-provider` but it makes sense to fix them all in one go just like `jackson-jaxrs-json-provider` was. It should also be fine to port it to `2.11` and `2.12` branches if you like. Please also note that I've changed the name of `jackson-jaxrs-xml-provider` module from `com.fasterxml.jackson.jaxrs.yaml` to `com.fasterxml.jackson.jaxrs.xml`. All other seem to be consistent.
Finally, please note that #124 seems to be breaking the `module-info.java` of all subprojects. After merging this PR, #124 should be adjusted so that it doesn't change any …
=> Allow multiple implementations of JAX-RS for all providers

json/src/moditect/module-info.java
Zero impact on backwards compatibility
https://github.com/FasterXML/jackson-databind/issues/2910
Adds support for the following maven coordinates in JMS : 
```
<dependency>
<groupId>jakarta.ws.rs</groupId>
<artifactId>jakarta.ws.rs-api</artifactId>
<version>3.0.0-M1</version>
</dependency>
<dependency>
<groupId>jakarta.ws.rs</groupId>
<artifactId>jakarta.ws.rs-api</artifactId>
<version>2.1.6</version>
</dependency>
<dependency>
<groupId>javax.ws.rs</groupId>
<artifactId>javax.ws.rs-api</artifactId>
<version>2.1.1</version>
</dependency>
```
=> Module-Info Enhancements - JAX-RS updates for Jakarta Release version

README.md, base/pom.xml, datatypes/pom.xml, json/pom.xml, json/src/moditect/module-info.java
Allow Jakarta Namespace Artifacts to be built and make note in the README.md 
* Creates shade artifact for Jakarta namespace
=> Jakarta Namespace Updates and Artifact Build

base/pom.xml, datatypes/pom.xml, json/pom.xml, pom.xml, xml/pom.xml
Runs the bundle plugin twice, once for the creation of the original bundle, and again for the changes to the jakarta packing.
The manifest files are placed in target/jakarta and are picked up by the shading and replaces the javax manifest
https://github.com/FasterXML/jackson-jaxrs-providers/issues/132
=> Create manifest files separately and reference in bundle plugin, THEN shade in the new manifest for Jakarta separately before install

base/pom.xml, cbor/pom.xml, datatypes/pom.xml, json/pom.xml, pom.xml, smile/pom.xml, xml/pom.xml, yaml/pom.xml
As per title: 2.12.2 release of JAX-RS components failed due to odd (and not yet understood) problem where in .pom files are missing, presumably due to post-processing done to fix references for OSGi manifest for of "jakarta" flavor implementations.
=> Remove Jakarta bundle fix added in #136 to try to fix #138

json/src/test/java/com/fasterxml/jackson/jaxrs/json/dw/WriteModificationsTestBase.java
`aposToQuotes` returns a string with the nondeterministic order of the map. Therefore, there are more possibilities of the combination of x and y.
=> fix a flaky test

base/src/main/java/com/fasterxml/jackson/jaxrs/base/ProviderBase.java, base/src/main/java/com/fasterxml/jackson/jaxrs/cfg/JaxRSFeature.java
=> Add `JaxRsFeature.READ_FULL_STREAM` to consume all content, on by default

base/src/main/java/com/fasterxml/jackson/jaxrs/cfg/MapperConfiguratorBase.java, cbor/src/main/java/com/fasterxml/jackson/jaxrs/cbor/CBORMapperConfigurator.java, json/src/main/java/com/fasterxml/jackson/jaxrs/json/JsonMapperConfigurator.java, release-notes/CREDITS-2.x, release-notes/VERSION-2.x, smile/src/main/java/com/fasterxml/jackson/jaxrs/smile/SmileMapperConfigurator.java, xml/src/main/java/com/fasterxml/jackson/jaxrs/xml/XMLMapperConfigurator.java, yaml/src/main/java/com/fasterxml/jackson/jaxrs/yaml/JacksonYAMLProvider.java, yaml/src/main/java/com/fasterxml/jackson/jaxrs/yaml/YAMLMapperConfigurator.java
I don't think the existing synchronized code stops multiple creations of mappers.
The new lock code double checks that the mappers are not initialized. The new locking is optimistic - we don't lock and only lock when we know we need to lazily create instances.
=> Use `ReentrantLock`s instead of synchronized blocks

base/src/main/java/com/fasterxml/jackson/jaxrs/cfg/MapperConfiguratorBase.java
see https://github.com/FasterXML/jackson-jakarta-rs-providers/pull/28
=> mark variables as volatile

pom.xml
Fix https://github.com/FasterXML/jackson-bom/issues/68
=> Add explicit `JUnit 4` dependency due to jackson-base refactoring

base/src/main/java/com/fasterxml/jackson/jaxrs/base/NoContentExceptionSupplier.java, base/src/main/java/com/fasterxml/jackson/jaxrs/base/ProviderBase.java, base/src/main/java/com/fasterxml/jackson/jaxrs/base/nocontent/JaxRS1NoContentExceptionSupplier.java, base/src/main/java/com/fasterxml/jackson/jaxrs/base/nocontent/JaxRS2NoContentExceptionSupplier.java, base/src/moditect/module-info.java, release-notes/VERSION-2.x
#134 is causing real problems for Apache Hadoop and a great deal of the ecosystem of Big Data libs and tools that need to support Hadoop.
A few developers have tried to get Hadoop off of JAXRS v1 (Jersey 1) but there has been no success. 
#134 has forced Hadoop to stick to Jackson 2.12 and that version is getting increasingly stale.
https://issues.apache.org/jira/browse/HADOOP-15984 is the related Hadoop issue.
=> Bring back code to support JAXRS v1 (revert #134 for 2.18)

cbor/src/main/java/com/fasterxml/jackson/jaxrs/cbor/JacksonCBORProvider.java, cbor/src/main/java/com/fasterxml/jackson/jaxrs/cbor/JacksonJaxbCBORProvider.java, json/src/main/java/com/fasterxml/jackson/jaxrs/json/JacksonJaxbJsonProvider.java, json/src/main/java/com/fasterxml/jackson/jaxrs/json/JacksonJsonProvider.java, release-notes/CREDITS-2.x, release-notes/VERSION-2.x, xml/src/main/java/com/fasterxml/jackson/jaxrs/xml/JacksonJaxbXMLProvider.java, xml/src/main/java/com/fasterxml/jackson/jaxrs/xml/JacksonXMLProvider.java, yaml/src/main/java/com/fasterxml/jackson/jaxrs/yaml/JacksonJaxbYAMLProvider.java, yaml/src/main/java/com/fasterxml/jackson/jaxrs/yaml/JacksonYAMLProvider.java
fix for issue: https://github.com/FasterXML/jackson-jaxrs-providers/issues/193
copied from: https://github.com/eclipse-ee4j/jersey/blob/2.x/media/json-binding/src/main/java/org/glassfish/jersey/jsonb/internal/JsonBindingProvider.java#L53
TODO, i guess we also need a test for this
=> fix for not encoding json as default

base/src/main/java/com/fasterxml/jackson/jaxrs/base/ProviderBase.java, release-notes/CREDITS-2.x, release-notes/VERSION-2.x
In my Dropwizard 2.x project, I noticed that POJO responses were serialized using the pretty printer, but Response objects were not. I debugged to this section of the code and found that the pretty-printer was not propagated here.
=> Propagate the pretty printer from the writer to the generator in `ProviderBase.writeTo()`
